# Generated by Django 5.2.7 on 2025-11-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('msg', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': "Yo'lovchi xabar matni",
                'verbose_name_plural': "Yo'lovchi xabar matnlari",
                'indexes': [models.Index(fields=['slug'], name='msg_app_bot_slug_8bf0e2_idx')],
            },
        ),
    ]
