# Generated by Django 5.2.7 on 2025-11-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(db_index=True, help_text='Telegram foydalanuvchisining unikal ID raqami.', unique=True)),
                ('full_name', models.CharField(help_text="Foydalanuvchining to‘liq ismi (Telegram'dan olinadi).", max_length=150)),
                ('username', models.CharField(blank=True, help_text="Foydalanuvchining Telegram username'i (@username).", max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, help_text='Foydalanuvchining afzal tili, masalan: uz, ru, en.', max_length=10, null=True)),
                ('is_blocked', models.BooleanField(default=False, help_text='Agar foydalanuvchi botni bloklagan bo‘lsa — True.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Foydalanuvchi tizimga birinchi marta kirgan vaqt.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi yangilangan vaqt.')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tg_id'], name='bot_app_tel_tg_id_73da14_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotUserService',
            fields=[
            ],
            options={
                'verbose_name': 'Bot foydalanuvchi servisi',
                'verbose_name_plural': 'Bot foydalanuvchi servislar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bot_app.telegramuser',),
        ),
    ]
